import { ArrowRight, Building2, CheckCircle2, Clock3, Heart, Leaf, MapPin, PackageCheck, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import Button from "../../components/ui/Button";
import SectionHeading from "../../components/ui/SectionHeading";
import Container from "../../components/layout/Container";
import Footer from "../../components/layout/Footer";
import Navbar from "../../components/layout/Navbar";

const stats = [["18,492", "meals shared this month"], ["6.4 t", "food rescued from waste"], ["185", "community partners"]];
const features = [
  [MapPin, "Connect locally", "Match surplus food with nearby verified organizations, while it is still fresh."],
  [Clock3, "Move at the right time", "Clear pickup windows and live updates keep every handoff simple."],
  [PackageCheck, "Track real impact", "See donations turn into meals and understand the difference you make."],
];

function HeroArtwork() {
  return <div className="relative mx-auto mt-14 w-full max-w-xl lg:mt-0"><div className="absolute -inset-8 -z-10 rounded-full bg-emerald-200/70 blur-3xl"/><div className="relative overflow-hidden rounded-[2rem] border border-white/70 bg-white/75 p-5 shadow-[0_30px_80px_rgba(7,62,48,.18)] backdrop-blur"><div className="mb-5 flex items-center justify-between"><span className="text-sm font-semibold text-slate-800">Ready for pickup</span><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">45 min left</span></div><div className="rounded-2xl bg-[linear-gradient(135deg,#d1fae5,#a7f3d0_55%,#fef3c7)] p-7"><div className="text-7xl">🥗</div></div><div className="mt-5 flex items-center justify-between"><div><p className="font-semibold text-slate-900">Fresh lunch boxes</p><p className="mt-1 text-sm text-slate-500">Serves 24 · Vegetarian</p></div><span className="grid size-11 place-items-center rounded-full bg-emerald-700 text-white"><ArrowRight size={19}/></span></div></div><div className="absolute -bottom-7 -left-8 rounded-2xl border border-white/80 bg-white px-4 py-3 shadow-lg"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-rose-100 text-rose-600"><Heart size={17} fill="currentColor"/></span><div><p className="text-sm font-bold text-slate-900">24 meals claimed</p><p className="text-xs text-slate-500">by Hope Community Center</p></div></div></div><div className="absolute -right-5 top-12 rounded-2xl border border-white/80 bg-white px-4 py-3 shadow-lg"><p className="text-xs font-medium text-slate-500">Food rescued today</p><p className="mt-1 text-xl font-bold text-emerald-700">1,284 kg</p></div></div>;
}

export default function LandingPage() {
  return <main id="top" className="overflow-hidden bg-[#fbfdfb] text-slate-900"><Navbar/>
    <section className="relative isolate bg-[radial-gradient(circle_at_75%_30%,#d1fae5_0,transparent_28%),linear-gradient(180deg,#f8fdf9_0%,#effaf3_100%)] pb-20 pt-32 sm:pb-28 sm:pt-40"><Container className="grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-emerald-900/10 bg-white/75 px-3 py-1.5 text-xs font-semibold text-emerald-800 shadow-sm"><Sparkles size={14}/> A kinder food system, together</div><h1 className="max-w-3xl text-balance text-5xl font-semibold leading-[.98] tracking-[-0.065em] text-slate-950 sm:text-6xl lg:text-7xl">Good food belongs <span className="text-emerald-700">on plates.</span></h1><p className="mt-6 max-w-xl text-pretty text-lg leading-8 text-slate-600">FoodShare makes it easy for businesses and communities to redirect quality surplus food to people who need it—before it becomes waste.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button className="px-6" onClick={() => { window.location.href = "/register"; }}>Share food <ArrowRight size={17}/></Button><Button variant="secondary" onClick={() => document.querySelector("#how-it-works")?.scrollIntoView({ behavior: "smooth" })}>See how it works</Button></div><div className="mt-9 flex items-center gap-3 text-sm text-slate-600"><div className="flex -space-x-2">{["#fcd5ce", "#cdeac0", "#bfd7ea", "#f8dda4"].map((color) => <span key={color} style={{ backgroundColor: color }} className="grid size-8 place-items-center rounded-full border-2 border-[#f8fdf9] text-[10px] font-bold text-slate-700">●</span>)}</div><span>Trusted by <strong className="font-semibold text-slate-800">2,400+ local changemakers</strong></span></div></div><HeroArtwork/></Container></section>
    <section className="border-y border-emerald-900/10 bg-white py-7"><Container className="grid grid-cols-1 divide-y divide-emerald-900/10 sm:grid-cols-3 sm:divide-x sm:divide-y-0">{stats.map(([value, label]) => <div key={label} className="py-4 text-center sm:py-1"><p className="text-3xl font-semibold tracking-[-.05em] text-emerald-800">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</Container></section>
    <section id="how-it-works" className="py-24 sm:py-32"><Container><SectionHeading eyebrow="Simple by design" title="From surplus to shared meals, without the friction." description="A calm, coordinated way to do good with food that already exists."/><div className="mt-14 grid gap-5 md:grid-cols-3">{[["01", "List your surplus", "Tell us what is available, how much, and when it can be collected."], ["02", "Match with a neighbor", "Verified organizations nearby receive the details and reserve the donation."], ["03", "Make the impact visible", "A simple handoff, a shared update, and a meal that reaches someone." ]].map(([number, title, copy]) => <article key={number} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><span className="text-sm font-bold text-emerald-700">{number}</span><h3 className="mt-12 text-xl font-semibold tracking-[-.03em] text-slate-900">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div></Container></section>
    <section id="impact" className="bg-emerald-950 py-24 text-white sm:py-32"><Container className="grid items-center gap-14 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Designed for real-world impact</p><h2 className="mt-4 max-w-lg text-balance text-4xl font-semibold leading-tight tracking-[-.05em] sm:text-5xl">Every detail makes sharing food easier.</h2><p className="mt-6 max-w-lg leading-7 text-emerald-100/75">No complicated workflows. Just the practical tools your team needs to do a generous thing, reliably and often.</p><Button variant="light" className="mt-8">Explore the platform <ArrowRight size={17}/></Button></div><div className="grid gap-4 sm:grid-cols-2">{features.map(([Icon, title, copy]) => <article key={title} className="rounded-3xl border border-white/10 bg-white/[.07] p-6 backdrop-blur"><Icon className="text-emerald-300" size={24}/><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-emerald-100/70">{copy}</p></article>)}<article className="rounded-3xl bg-emerald-300 p-6 text-emerald-950"><Leaf size={25}/><p className="mt-8 text-2xl font-semibold tracking-[-.04em]">Less waste. More care.</p><p className="mt-3 text-sm leading-6 text-emerald-950/70">The best climate action is often closer than you think.</p></article></div></Container></section>
    <section id="for-organizations" className="py-24 sm:py-32"><Container><SectionHeading eyebrow="Built for every helper" title="One shared network. Different ways to make a difference."/><div className="mt-14 grid gap-5 md:grid-cols-3">{[[Building2,"Food businesses","Turn surplus into meaningful local impact, with a donation flow your team can finish in minutes."],[UsersRound,"Community organizations","Find suitable food nearby and coordinate collections without endless calls and messages."],[ShieldCheck,"Delivery volunteers","See exactly what needs moving, when it matters, and where it will help."]].map(([Icon,title,copy]) => <article key={title} className="group rounded-3xl bg-emerald-50 p-7"><span className="grid size-12 place-items-center rounded-2xl bg-white text-emerald-700 shadow-sm"><Icon size={23}/></span><h3 className="mt-7 text-xl font-semibold tracking-[-.03em]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p><a href="#get-started" className="mt-6 inline-flex items-center gap-1 text-sm font-bold text-emerald-800">Learn more <ArrowRight className="transition group-hover:translate-x-1" size={16}/></a></article>)}</div></Container></section>
    <section id="get-started" className="pb-24 sm:pb-32"><Container><div className="relative overflow-hidden rounded-[2rem] bg-[linear-gradient(120deg,#075a47,#0b7a62)] px-7 py-14 text-center text-white sm:px-14 sm:py-20"><div className="absolute -right-12 -top-12 size-56 rounded-full bg-emerald-300/20 blur-2xl"/><div className="relative mx-auto max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-200">Start today</p><h2 className="mt-4 text-balance text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Have food to share? We’ll help it find its next meal.</h2><p className="mt-5 text-lg leading-8 text-emerald-50/80">Join the local network turning surplus into care.</p><Button className="mt-8 bg-white text-emerald-900 hover:bg-emerald-50" onClick={() => { window.location.href = "/register"; }}>Create a free account <ArrowRight size={17}/></Button></div></div></Container></section><Footer/>
  </main>;
}
